name: test-job-start
on: [fork, workflow_dispatch]
jobs:
  repo_forked:
    permissions: 
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: Mozzart88/test-action@main
        with:
         repo-token: ${{ secrets.GITHUB_TOKEN }}
